// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1649451178);
user_pref("app.update.lastUpdateTime.region-update-timer", 1649451418);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1649450938);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1649451058);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1649450967);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1649451298);
user_pref("browser.region.update.updated", 1649450933);
user_pref("browser.search.region", "ET");
user_pref("browser.theme.dark-toolbar-theme", false);
user_pref("calendar.timezone.local", "Africa/Addis_Ababa");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1649450936896");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.cache.lastUpdate", 1649451180);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20220106182030");
user_pref("extensions.lastAppVersion", "91.5.0");
user_pref("extensions.lastPlatformVersion", "91.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"0826c2fd-e4b1-47c1-8bf5-b8ff85d6e087\",\"google@search.mozilla.org\":\"8e8db425-7acf-4f9b-bc4b-fb6fc0d8e35d\",\"ddg@search.mozilla.org\":\"a66f80ef-be8b-4c24-9754-af841da3e191\",\"amazondotcom@search.mozilla.org\":\"1afd7f6a-d2df-4fff-85b6-329029e65c21\",\"wikipedia@search.mozilla.org\":\"9874bbab-c1b0-427c-a9bb-fc093696ac39\",\"bing@search.mozilla.org\":\"138676c2-f2f9-49f9-8943-df326b9c0f3f\"}");
user_pref("idle.lastDailyNotification", 1649451232);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 30);
user_pref("mailnews.database.global.datastore.id", "7e179977-abf1-4ac0-bbf9-756c0c64be1");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "91.5.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("places.database.lastMaintenance", 1649451232);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("services.settings.clock_skew_seconds", -16318);
user_pref("services.settings.last_etag", "\"1648185887941\"");
user_pref("services.settings.last_update_seconds", 1649467376);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1649467376);
user_pref("services.settings.thunderbird.search-config.last_check", 1649467376);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1649467376);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1649451232);
user_pref("toolkit.telemetry.cachedClientID", "bb348490-854c-4c2c-bfe9-54974049fab8");
user_pref("toolkit.telemetry.previousBuildID", "20220106182030");
