// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupRolloutPrefs.javascript.options.wasm_caching", false);
user_pref("app.normandy.user_id", "fc01e5f4-fe51-4a1a-8f58-44da72daeb77");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1649508536);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1649508532);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1649508514);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1649508566);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{8049b73e-e654-4364-a804-fc4f43994359}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1649508506);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 125);
user_pref("browser.newtabpage.activity-stream.impressionId", "{73a48f5c-ac62-4fa5-beb9-a0936e4aeff2}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1649508510);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1649508563484");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1649510354484");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1649508534561");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1649530134561");
user_pref("browser.search.region", "ET");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1649508516");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20220330194208");
user_pref("browser.startup.homepage_override.mstone", "99.0");
user_pref("browser.startup.lastColdStartupCheck", 1649508509);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1649508517166");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "99.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "ET");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "cdaf887e5b494a2086823e892b7926f2");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1649508509);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20220330194208");
user_pref("extensions.lastAppVersion", "99.0");
user_pref("extensions.lastPlatformVersion", "99.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"794d6cb1-388d-48e9-9ad8-6ec2e0e94c82\",\"formautofill@mozilla.org\":\"637cf6ff-0adb-4684-b2f7-4e80da55e4d1\",\"pictureinpicture@mozilla.org\":\"22c6acd7-0678-464f-883d-f8a9eb5fddb9\",\"screenshots@mozilla.org\":\"9cde68ab-6801-44ba-9bb4-bc6f42c69715\",\"webcompat-reporter@mozilla.org\":\"c3de8048-a6e1-493b-891a-d6952f7718b3\",\"webcompat@mozilla.org\":\"24869524-57e0-43b8-ab78-2fe08fc02447\",\"default-theme@mozilla.org\":\"010288d6-98d6-428c-aaa9-34b621d98bdd\",\"addons-search-detection@mozilla.com\":\"ddb6a853-e381-4ce2-8024-eea16f5a5587\",\"google@search.mozilla.org\":\"cad2cd02-45b0-4cd8-81a9-3a28b649f5f8\",\"amazondotcom@search.mozilla.org\":\"4694e9f6-ec96-486d-863a-67d80433ea3b\",\"wikipedia@search.mozilla.org\":\"e890a4fb-88a2-4ad3-86bc-d15a0599dc47\",\"bing@search.mozilla.org\":\"07fe84f1-a23a-4700-abbe-be99dcde3cc1\",\"ddg@search.mozilla.org\":\"bf427f8f-6b06-4672-96e8-974dc6e6b5ac\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1649508519);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "c1214832-cad1-4489-aef2-a8ed15faa74f");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1649508502);
user_pref("toolkit.telemetry.cachedClientID", "e2d011e8-652e-4c39-ac15-70347087d430");
user_pref("toolkit.telemetry.previousBuildID", "20220330194208");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
